on: 
  push:
  workflow_dispatch:

name: Site Deployment

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
      # - name: Deploy site
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_PAT }}
      #     publish_dir: public
      #     force_orphan: true
      #     user_name: Auto5958
      #     user_email: 69833949+Auto5958@users.noreply.github.com
      # - name: Deploy site
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: public
      #     force_orphan: true
      # - name: Deploy site
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_PAT }}
      #     publish_dir: public
      #     force_orphan: true
      #     user_name: Auto5958
      #     user_email: 69833949+Auto5958@users.noreply.github.com
      # - name: Deploy site
      #   uses: maxheld83/ghpages@v0.3.0
      #   env:
      #     BUILD_DIR: public
      #     GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      # - name: Deploy site
      #   uses: maxheld83/ghpages@v0.3.0
      #   env:
      #     BUILD_DIR: public
      #     GH_PAT: ${{ secrets.GH_PAT }}